#!/bin/bash


valid_options=true
git_repo=false
venv=false

while getopts "gvh" opt; do
  case $opt in
    g)
      git_repo=true
      ;;
    v)
      venv=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      valid_options=false
      ;;
  esac
done


if $valid_options; then
  
  shift $((OPTIND - 1))

  function create_git_repo() {
    git init
    touch .gitignore
  }

  function git_add_commit() {
    git add .
    git commit -m "Initial commit"
  }

  function create_venv() {
    python3 -m venv venv
  }

  for arg in "$@"; do
    cd ~/Desktop/PythonProjects
    mkdir $arg
    cd $arg
    touch main.py
    
    if $venv; then
      echo "Creating Python virtual environment..."
      create_venv
    fi

    if $git_repo; then
      echo "Initializing git repository..."
      create_git_repo
      if $venv; then
        echo "venv/" >> .gitignore
      fi
      git_add_commit
    fi
    
  done
fi